version: '3.9'

services:
  db:
    image: ankane/pgvector
    container_name: alfred_db
    restart: always
    environment:
      POSTGRES_USER: alfred
      POSTGRES_PASSWORD: alfred123
      POSTGRES_DB: alfred_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
